apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app : {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.appname }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  type: {{ .Values.service.type }}