apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: gateway-deployment
  labels: 
    app: gateway
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: gateway
  template: 
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers: 
        - name: gateway
          image: dockeriheme/gateway
          env:
           - name: NODE_ENV
             value: "production"
           - name: "CONNECTION_STRING"
             valueFrom: 
               secretKeyRef:
                  name: db
                  key: "CONNECTION_STRING"
           - name: "ORDER_HOST"
             valueFrom:
              configMapKeyRef:
                name: global-configmap
                key: ORDER_HOST
           - name: "PRODUCT_HOST"
             valueFrom:
              configMapKeyRef:
                name: global-configmap
                key: PRODUCT_HOST
          resources:  
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports: 
            - containerPort: 3000
